spring:
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/houses_database
    username: postgres
    password: admin

  hibernate:
    hbm2ddl:
      auto: none
    dialect: org.hibernate.dialect.PostgreSQLDialect